### ISSUE TITLE
Issue with Base62 autogenerated Id

### ISSUE THREAD

**Issue by papakay** [stevedomin/bigflake#13]
I really want to commend the great work done on this library.

After adding this to my project, I have some issues with related fields key. (Ecto 3.0)

```
** (exit) an exception was raised:
    ** (Ecto.ChangeError) value `"009fsGk9JPqZZPXJjoS8"` for `JournalManager.Accounts.Profile.user_id` in `insert` does not match type :id
        (ecto) lib/ecto/repo/schema.ex:932: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:941: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
        (stdlib) maps.erl:257: :maps.fold_1/3
        (ecto) lib/ecto/repo/schema.ex:939: Ecto.Repo.Schema.dump_fields!/5
        (ecto) lib/ecto/repo/schema.ex:872: Ecto.Repo.Schema.dump_changes!/6
        (ecto) lib/ecto/repo/schema.ex:257: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
        (ecto) lib/ecto/association.ex:657: Ecto.Association.Has.on_repo_change/5
        (ecto) lib/ecto/association.ex:408: Ecto.Association.on_repo_change/7
        (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/association.ex:387: Ecto.Association.on_repo_change/4
        (ecto) lib/ecto/repo/schema.ex:832: Ecto.Repo.Schema.process_children/5
        (ecto) lib/ecto/repo/schema.ex:917: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto_sql) lib/ecto/adapters/sql.ex:820: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
        (db_connection) lib/db_connection.ex:1355: DBConnection.run_transaction/4
        (journal_manager) lib/journal_manager_web/controllers/user_controller.ex:47: JournalManagerWeb.UserController.create/2
        (journal_manager) lib/journal_manager_web/controllers/user_controller.ex:1: JournalManagerWeb.UserController.action/2
        (journal_manager) lib/journal_manager_web/controllers/user_controller.ex:1: JournalManagerWeb.UserController.phoenix_controller_pipeline/2
        (journal_manager) lib/journal_manager_web/endpoint.ex:1: JournalManagerWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (journal_manager) lib/journal_manager_web/endpoint.ex:1: JournalManagerWeb.Endpoint.plug_builder_call/2
```

Please how can i resolve this issue?

**Comment by papakay** [comment]
I was able to figure it out. I needed to add `@foreign_key_type Ecto.Bigflake.Base62` to each schema. It worked fine after adding this to my schema.

**Comment by stevedomin** [comment]
Glad you figured it out!
